# Importing Libraries

In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data Pre-processing

In [30]:
data = pd.read_csv("/kaggle/input/agencyperformance/finalapi.csv")
threshold = 1000  # For example, you may consider 'high retention' if RETENTION_POLY_QTY > 1000, otherwise 'low retention'

# Create a new binary target variable based on the threshold
data['target_variable'] = np.where(data['RETENTION_POLY_QTY'] > threshold, 1, 0)

x = data[['STAT_PROFILE_DATE_YEAR', 'NB_WRTN_PREM_AMT']].values  # Extracting features (columns 2 and 3) into variable x
y = data['target_variable'].values  # Extracting target variable (column 4) into variable y

# Importing dataset into a DataFrame (assuming 'dataset' is your dataset)
df = pd.DataFrame(data)

# Splitting the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)
print(x_train)

[[-0.06140133 -0.06540313]
 [ 0.25827481 -0.22383849]
 [ 0.25827481 -0.22383849]
 ...
 [ 0.57795094  0.48174301]
 [-1.02042974 -0.22383849]
 [ 0.57795094 -0.22383849]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier( criterion = 'entropy' , random_state = 0 )
classifier.fit( x_train , y_train )

DecisionTreeClassifier(criterion='entropy', random_state=0)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Predicting The Test Result

In [33]:
y_pred = classifier.predict(x_test)
print(y_pred)

[0 0 0 ... 0 0 0]


# Creation of Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[49916  1287]
 [ 1579   550]]
